[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:create_app()"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"